POST https://api.testmail.app/api/graphql
Accept: application/json
Origin: https://api.testmail.app
Authorization: Bearer 383a008d-4fc8-4c15-a7f9-f23d981089de
Content-Type: application/json

{
    "query": "query { inbox(namespace: \"s5sys\") { emails { subject from to text } } }"
}

###
