POST https://api.testmail.app/api/graphql
Accept: application/json
Origin: https://api.testmail.app
Authorization: Bearer 383a008d-4fc8-4c15-a7f9-f23d981089de
Content-Type: application/json

{
    "query": "query { inbox(namespace: \"s5sys\") { emails { subject from to text } } }"
}

###
#server {
#    listen 80;
#    server_name api.devhub.hackclub.app;
#
#    root /var/www/html/jowxidea/public;
#    index index.php index.html;
#
#    location / {
#        try_files $uri $uri/ /index.php?$query_string;
#    }
#
#    location ~ \.php$ {
#        include snippets/fastcgi-php.conf;
#        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
#    }
#
#    location ~ /\.ht {
#        deny all;
#    }
#}
