POST https://api.testmail.app/api/graphql
Accept: application/json
Origin: https://api.testmail.app
Authorization: Bearer bd8bb9d4-ff58-4626-a141-0259b8ec444c
Content-Type: application/json

{
    "query": "query { inbox(namespace: \"9gwbk\") { emails { subject from to text } } }"
}

